# Docker 镜像 CI 工作流
name: Docker 镜像构建与推送

# 触发条件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    # 在最新的 Ubuntu 环境中运行
    runs-on: ubuntu-latest
    
    steps:
      # 检出代码仓库
      - name: 检出代码
        uses: actions/checkout@v4
      
      # 登录到 Docker Hub（仅在推送事件时执行，PR 时不执行）
      - name: 登录 Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 构建 Docker 镜像
      - name: 构建 Docker 镜像
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/auto-update-jd-cookie:latest
      
      # 推送 Docker 镜像到 Docker Hub（仅在推送事件时执行，PR 时不执行）
      - name: 推送到 Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/auto-update-jd-cookie:latest